### ISSUE TITLE
Options specified in a nav item are being lost upon rendering

### ISSUE THREAD

**Issue by gltarsa** [jbox-web/simple_navigation_bootstrap#1]
Thanks for developing this package.  A similar package, [simple-navigation-bootstrap](https://github.com/pdf/simple-navigation-bootstrap) is looking for a maintainer.  You should consider taking it over.  Your code seems better organized.

I am running into a problem where options, like icon: [fa fa-ticket] to disappear when our app uses this package. That means code like this:

```
    primary.item :ticket,
      "Ticket",
      url_for('//mycompany/ticket'),
      link_html: { target: '_blank' },
      icon: ['fa fa-ticket'],
      if: -> { can? :create, Ticket }
```
Now appears to ignore the `icon: ['fa fa-ticket']` option. That snippet used to render as a small ticket icon followed by the word "Ticket" now renders as just "Ticket" with no icon.  No CSS for the icon is present in the view.

I am investigating the problem, but cannot promise I will be able to deliver a fix.

**Comment by n-rodriguez** [comment]
Hi! It's not the right format of options. It should be 

```ruby
primary.item :ticket, { icon: 'fa fa-ticket', text: 'Ticket' }, url_for('//mycompany/ticket'), link_html: { target: '_blank' }, if: -> { can? :create, Ticket }
```

**Comment by gltarsa** [comment]
Thanks.  I was finally able to test out the change and that does indeed fix the problem.
