### ISSUE TITLE
Bootstrap4 Renderer not registering

### ISSUE THREAD

**Issue by jaredjackson** [jbox-web/simple_navigation_bootstrap#6]
For some reason I haven't been able to find, the Bootstrap4 renderer is not registering in my app. To try and figure this out, I added a test for the renderer registers for Bootstrap4 and got the same: 

`"Uninitialized constant "SimpleNavigationBootstrap::Bootstrap4"`

I have tried my best to figure out why the Boostrap4 renderer isn't registering but no luck so far. I'm sure I'm overlooking something simple and will keep trying but thought I'd go ahead and report it.

**Comment by jaredjackson** [comment]
Ah ... found a clue ... my Gemfile simply had the following:

`gem 'simple_navigation_bootstrap'`

The gem installed with that command did not contain the bootrap4.rb file nor the registration initialization code.

When I added the gem with:

`gem 'simple_navigation_bootstrap', git: "https://github.com/jbox-web/simple_navigation_bootstrap.git"`

... the correct version of the gem was installed.

**Comment by n-rodriguez** [comment]
I just made a new release : 1.2.0
