### ISSUE TITLE
When I try to install your gem...

### ISSUE THREAD

**Issue by gloufy** [jbox-web/simple_navigation_bootstrap#7]
Hi

I've got this error...

Could not find gem 'simple-navigation-bootstrap' in https://github.com/jbox-web/simple_navigation_bootstrap.git (at master@52625c4).
The source does not contain any versions of 'simple-navigation-bootstrap'

gem 'simple-navigation-bootstrap',git: 'https://github.com/jbox-web/simple_navigation_bootstrap.git' 

and if I don't put the "git url" it's the 1.0.0 version which is installed, I don't understand why.
Thank for your help

**Comment by n-rodriguez** [comment]
Hi there! 

This is weird... did you try `bundle update simple-navigation-bootstrap`?
